[project]
name = "data-engineering-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.6",
    "polars>=1.44.2",
    "requests>=2.34.2",
]

[project.scripts]
data-engineering-journey = "data_engineering_journey:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
